apiVersion: v1
kind: Pod
metadata:
  name: envs
spec:
  containers:
    - name: sise
      image: quay.io/openshiftlabs/simpleservice:0.5.0
      ports:
        - containerPort: 9876
      env:
        - name: SIMPLE_SERVICE_VERSION
          value: "1.0"

# /env endpoint can inspect all environment variables.
# Use with kpf, kubectl port-forward is good.
