apiVersion: v1
kind: Pod
metadata:
  name: labelex
  labels:
    env: development
spec:
  containers:
    - name: sise
      image: quay.io/openshiftlabs/simpleservice:0.5.0
      ports:
        - containerPort: 9876

# kubectl label pods labelex owner=michael
# kubectl get pods --selector owner=michael

# Set labels, then use to filter pods.
