apiVersion: apps/v1
kind: Deployment
metadata:
  name: sise-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sise
  template:
    metadata:
      labels:
        app: sise
    spec:
      containers:
        - name: sise
          image: quay.io/openshiftlabs/simpleservice:0.5.0
          ports:
            - containerPort: 9876
---
apiVersion: v1
kind: Service
metadata:
  name: simpleservice
spec:
  ports:
    - port: 80 # Which is forward out of the Pod.
      targetPort: 9876 # Which is Pod listening on.
  selector:
    app: sise

# https://kubernetes.io/zh/docs/concepts/services-networking/service/#publishing-services-service-types
# Default services type is `ClusterIP`, which can only access from inner cluster.

# kubectl port-forward service/simpleservice 8080:80
# Port forwarding to localhost:8080, access it and have fun!
