apiVersion: v1
kind: Pod
metadata:
  name: twocontainers
spec:
  # Default value is always, so exit with 0 also trigger restart.
  restartPolicy: OnFailure
  containers:
    - name: sise
      image: quay.io/openshiftlabs/simpleservice:0.5.0
      ports:
        - containerPort: 9876
    - name: shell
      image: centos:7
      command:
        - "bin/bash"
        - "-c"
        - "sleep 10000"

# Change sleep timeout to 10 and watch the events!
# The container will restart automatically.

# https://stackoverflow.com/questions/51931113/kubectl-get-events-only-for-a-pod
# kubectl get events --field-selector involvedObject.name=twocontainers
