apiVersion: v1
kind: Pod
metadata:
  name: twocontainers
spec:
  containers:
    - name: sise
      image: quay.io/openshiftlabs/simpleservice:0.5.0
      ports:
        - containerPort: 9876
    - name: shell
      image: centos:7
      command:
        - "bin/bash"
        - "-c"
        - "sleep 10000"

# Change sleep timeout to 10 and watch the events!
# The container will restart automatically.
